services:
  frontend:
    build:
      context: ../expensy_frontend
    ports:
      - "3000:3000"
    env_file:
      - ../expensy_frontend/.env.production
    depends_on:
      - backend

  backend:
    build:
      context: ../expensy_backend
    ports:
      - "8706:8706"
    env_file:
      - ../expensy_backend/.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ../expensy_backend/.env  
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
      #MONGO_INITDB_DATABASE: expeny
    command: ["mongod", "--bind_ip_all"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ../expensy_backend/.env    
    #environment:
      #REDIS_PASSWORD: someredispassword 
    command: ["redis-server", "--requirepass", "someredispassword"]

volumes:
  mongo-data: